export const timelinePhases = [
  {
    id: 'phase-1',
    phase: 'Phase 1',
    title: 'Make It Real',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'Moved data from browser storage to a real database. Anonymous auth. Dual storage mode with automatic fallback.',
    detail: [
      'Supabase integration with anonymous authentication — users get a database-backed account without signing up.',
      'Normalized schema: grants, budget_categories, and expenses tables with Row Level Security.',
      'Dual storage: cloud mode (Supabase) with localStorage fallback if the database is unavailable.',
      'One-time migration: existing browser data automatically moves to the cloud on first connection.',
      'Confidence score: 87/100.',
    ],
    lesson: 'Start with the infrastructure that makes everything else possible. Data persistence is the foundation.',
  },
  {
    id: 'phase-2',
    phase: 'Phase 2',
    title: 'Make It Useful — FAILED',
    date: 'Feb 2026',
    status: 'failure',
    outcome: 'Built multi-grant management, narrative guidance, and JSON export — then it all broke on deploy.',
    detail: [
      'Three features built: multi-grant management (list, create, delete, switch), structured narrative guidance (5 fields with funder-focused hints), and JSON data export.',
      'Code was correct — React logic and data flow worked fine in development.',
      'On deployment to Netlify: blank page. No visible error.',
      'Debugging revealed: the Babel-in-browser compiler executed scripts before the Supabase library loaded from CDN.',
      '7+ attempts to fix the timing bug. Classic symptom-chasing — each fix revealed a new layer of the problem.',
      'The root cause wasn\'t a code bug. It was an architectural problem: CDN + Babel-in-browser creates untestable, timing-dependent execution.',
      'Confidence score was 85/100 — but it didn\'t capture infrastructure risk.',
    ],
    lesson: 'A high confidence score doesn\'t mean everything will work. The scoring missed infrastructure reliability as a dimension.',
  },
  {
    id: 'phase-2-rr',
    phase: 'Review & Reflect',
    title: 'The Andon Cord',
    date: 'Feb 2026',
    status: 'recovery',
    outcome: 'Stopped. Found the real problem. Decided to rebuild the foundation instead of patching symptoms.',
    detail: [
      'Review & Reflect triggered: bug took >5 attempts to fix, phase failed user acceptance testing.',
      'Root cause identified: Babel standalone compiles scripts in a timing context where CDN-loaded libraries aren\'t available yet. This entire class of bugs is unfixable within the current architecture.',
      'Decision: revert all Phase 2 code. Preserve the research and design (they were sound). Rebuild the delivery infrastructure.',
      'Constitution amended: "No build tools" constraint removed. Replaced with: "Build tools are permitted when evidence shows they prevent a class of bugs."',
      'New phases inserted: 2a (rebuild foundation with Vite) and 2b (re-implement features).',
      'All Phase 2 code preserved as reference for re-implementation.',
    ],
    lesson: 'This is the methodology working exactly as designed. The safety mechanism caught a real problem and guided the recovery. The failure made the project stronger.',
    expanded: true,
  },
  {
    id: 'phase-2a',
    phase: 'Phase 2a',
    title: 'Make It Buildable',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'Replaced CDN + Babel with Vite + React. Added automated smoke tests. Cloud mode finally verified working.',
    detail: [
      'Vite 7 + React 19 + Tailwind CSS 3 replaced the CDN + Babel-in-browser architecture.',
      'Supabase CLI installed for local development and testing.',
      '8 automated smoke tests including live Supabase anonymous auth verification.',
      'The Babel timing bug was eliminated entirely — ES module imports guarantee correct execution order.',
      'User acceptance test: PASS. Cloud mode works. Data persists across sessions.',
    ],
    lesson: 'Sometimes the highest-value thing to build is infrastructure. A solid foundation makes everything that follows easier and more reliable.',
  },
  {
    id: 'phase-2b',
    phase: 'Phase 2b',
    title: 'Make It Useful (rebuilt)',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'Re-implemented all Phase 2 features on the new foundation. Multi-grant, narrative guidance, CSV import, grant archiving.',
    detail: [
      'Multi-grant management: list view with cards, create, delete, switch between grants.',
      'Structured narrative guidance: 5 prompted fields with funder-focused hints.',
      'CSV bank statement import: 3-step wizard with auto-detect for Australian bank formats.',
      'Grant status and archiving: draft/active/acquitted with filter tabs.',
      '13 automated smoke tests. All passing.',
      'Confidence score: 92-94/100.',
      'User acceptance test: PASS on all items.',
    ],
    lesson: 'Good research and design survive architectural changes. The Phase 2 analysis was reused almost entirely — only the delivery changed.',
  },
  {
    id: 'phase-3',
    phase: 'Phase 3',
    title: 'Make It Trustworthy',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'About page, privacy policy, FAQ, data deletion. Trust through transparency.',
    detail: [
      'About page with Kamunity branding, mission statement, and "what\'s the catch?" section.',
      'Privacy policy in plain English — what data is collected, where it\'s stored, who has access.',
      'FAQ: 10 questions addressing real treasurer concerns.',
      'Delete All My Data: one-click deletion of cloud and local data.',
      'Confidence score: 91/100.',
    ],
    lesson: 'Trust isn\'t a feature — it\'s a collection of decisions. Plain language, honest answers, and user control over their data.',
  },
  {
    id: 'phase-4',
    phase: 'Phase 4',
    title: 'Make It Findable',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'SEO, landing hero, deployed to grants-hub.netlify.app. Now discoverable by people who need it.',
    detail: [
      'SEO meta tags, Open Graph, Twitter Card, JSON-LD structured data.',
      'Landing hero: marketing-style empty state for first-time visitors.',
      'Netlify deploy configuration, robots.txt, sitemap.xml.',
      'Deployed and live at grants-hub.netlify.app.',
      'Confidence score: 92/100.',
    ],
    lesson: 'A great tool nobody can find helps nobody. Discoverability is a feature, not an afterthought.',
  },
  {
    id: 'phase-5',
    phase: 'Phase 5',
    title: 'User Accounts',
    date: 'Feb 2026',
    status: 'success',
    outcome: 'Email OTP authentication. Anonymous users can save their account permanently. 3 post-build bugs found and fixed.',
    detail: [
      'Email OTP (one-time password) authentication — no passwords to remember.',
      'Anonymous-to-permanent account conversion: users build trust with the tool first, then optionally save their account.',
      '3 bugs found during testing: OTP input length, double-try token consumption, misleading rate limit message. All fixed.',
      'Confidence score: 87/100.',
      'Desktop acceptance test: PASS. Phone test: rate-limited (not a code bug).',
    ],
    lesson: 'Let users build trust before asking for commitment. Anonymous-first is a sovereignty-respecting pattern.',
  },
]
