// Generate downloadable Word-compatible (.doc) templates
// Word/Google Docs can open HTML files saved with .doc extension

function downloadHtmlAsDoc(filename, html) {
  const fullHtml = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8">
    <style>
      body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #1a1a1a; line-height: 1.6; margin: 2cm; }
      h1 { font-size: 18pt; color: #0d1b2a; border-bottom: 2px solid #2ec4b6; padding-bottom: 6pt; }
      h2 { font-size: 14pt; color: #0d1b2a; margin-top: 18pt; }
      h3 { font-size: 12pt; color: #0d1b2a; }
      table { border-collapse: collapse; width: 100%; margin: 12pt 0; }
      th { background-color: #f0f0f0; font-weight: bold; text-align: left; padding: 6pt 8pt; border: 1pt solid #ccc; }
      td { padding: 6pt 8pt; border: 1pt solid #ccc; vertical-align: top; }
      .input-field { border-bottom: 1pt solid #999; min-width: 200pt; display: inline-block; padding: 2pt 4pt; color: #666; }
      .checkbox { margin-right: 6pt; }
      .note { font-size: 9pt; color: #888; font-style: italic; }
      .section { margin-bottom: 18pt; }
      ul { padding-left: 18pt; }
      li { margin-bottom: 4pt; }
      .highlight { background-color: #fff3cd; padding: 8pt; border-left: 3pt solid #ffc107; margin: 12pt 0; }
      .green-box { background-color: #d4edda; padding: 8pt; border-left: 3pt solid #28a745; margin: 12pt 0; }
      .red-box { background-color: #f8d7da; padding: 8pt; border-left: 3pt solid #dc3545; margin: 12pt 0; }
    </style></head><body>${html}</body></html>`;

  const blob = new Blob(['\uFEFF' + fullHtml], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadAIPolicyTemplate() {
  const html = `
    <h1>AI Use Policy Template</h1>
    <p class="note">Generated by the Kamunity AI Safety Starter Kit. Fill in the highlighted fields and share with your team.</p>

    <h2><span class="input-field">[Your Organisation Name]</span> AI Use Guidelines</h2>
    <p>Last updated: <span class="input-field">[date]</span></p>

    <div class="section">
      <h3>Purpose</h3>
      <p>These guidelines help our team use AI tools safely and effectively. We encourage experimentation with AI for appropriate tasks, while protecting our clients' privacy and our organisation's integrity.</p>
    </div>

    <div class="section">
      <h3>Applies To</h3>
      <p>All staff, volunteers, contractors, and board members.</p>
    </div>

    <div class="green-box">
      <h3>You CAN use AI for:</h3>
      <ul>
        <li>Drafting social media posts, newsletters, and general communications</li>
        <li>Brainstorming ideas and planning</li>
        <li>Summarising long documents (that don't contain personal information)</li>
        <li>Research and learning about topics relevant to your work</li>
        <li>Proofreading and editing your own writing</li>
        <li>Creating templates and checklists</li>
        <li><span class="input-field">[Add your own approved uses]</span></li>
      </ul>
    </div>

    <div class="red-box">
      <h3>Do NOT enter into AI tools:</h3>
      <ul>
        <li>Client names, case notes, or any personally identifying information</li>
        <li>Confidential organisational information (financial details, board minutes, HR matters)</li>
        <li>Passwords, access credentials, or security information</li>
        <li>Information about vulnerable people (family violence, health, disability, youth)</li>
        <li>Legal documents or content requiring professional advice</li>
        <li>Anything you wouldn't paste into a public website</li>
      </ul>
    </div>

    <div class="highlight">
      <h3>Always Remember:</h3>
      <ul>
        <li>AI can be wrong. Always check important facts and figures</li>
        <li>AI-generated content should be reviewed before publishing</li>
        <li>If you're unsure whether something is safe to enter, ask <span class="input-field">[designated person]</span> first</li>
        <li>We review these guidelines every <span class="input-field">[6 months / annually]</span></li>
      </ul>
    </div>

    <div class="section">
      <h3>Approved AI Tools</h3>
      <table>
        <tr><th>Tool</th><th>Approved Use</th><th>Privacy Settings Required</th></tr>
        <tr><td><span class="input-field">[e.g. ChatGPT]</span></td><td><span class="input-field">[e.g. Content drafting]</span></td><td><span class="input-field">[e.g. Training opt-out enabled]</span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      </table>
    </div>

    <p class="note">Questions? Contact <span class="input-field">[name/role]</span>. This policy was created using the Kamunity AI Safety Starter Kit (kamunity-audit.netlify.app).</p>
  `;
  downloadHtmlAsDoc('AI-Use-Policy-Template.doc', html);
}

export function downloadToolInventoryTemplate() {
  const html = `
    <h1>Digital Tool Inventory</h1>
    <p class="note">Generated by the Kamunity Vendor Lock-in Assessment. List all digital tools your organisation uses.</p>

    <table>
      <tr>
        <th>Tool Name</th>
        <th>What It Does</th>
        <th>Monthly Cost</th>
        <th>Who Manages It</th>
        <th>Can You Export Data?</th>
        <th>Contract End Date</th>
        <th>Lock-in Risk (H/M/L)</th>
        <th>Notes</th>
      </tr>
      ${Array(15).fill('').map(() => '<tr>' + Array(8).fill('<td>&nbsp;</td>').join('') + '</tr>').join('\n')}
    </table>

    <div class="section">
      <h3>Summary</h3>
      <p>Total tools: <span class="input-field">____</span></p>
      <p>Total monthly cost: $<span class="input-field">____</span></p>
      <p>Tools with no export option: <span class="input-field">____</span></p>
      <p>Tools managed by only one person: <span class="input-field">____</span></p>
    </div>

    <div class="highlight">
      <h3>Key Findings</h3>
      <p><span class="input-field">[Summarise your biggest risks and recommended actions]</span></p>
    </div>

    <p class="note">Created using the Kamunity Digital Sovereignty Toolkit (kamunity-audit.netlify.app).</p>
  `;
  downloadHtmlAsDoc('Tool-Inventory-Template.doc', html);
}

export function downloadDataMapTemplate() {
  const html = `
    <h1>Data Location Map</h1>
    <p class="note">Generated by the Kamunity Data Ownership Checklist. Map where your organisation's data lives.</p>

    <h2>1. Data Locations</h2>
    <table>
      <tr>
        <th>Location / Platform</th>
        <th>Type of Data</th>
        <th>Account Owner</th>
        <th>Backed Up?</th>
        <th>Data Sensitivity</th>
        <th>Stored in Australia?</th>
      </tr>
      ${Array(12).fill('').map(() => '<tr>' + Array(6).fill('<td>&nbsp;</td>').join('') + '</tr>').join('\n')}
    </table>

    <h2>2. Admin Access Register</h2>
    <table>
      <tr>
        <th>Account / Platform</th>
        <th>Admin User 1</th>
        <th>Admin User 2</th>
        <th>Password Manager?</th>
        <th>Last Access Review</th>
      </tr>
      ${Array(10).fill('').map(() => '<tr>' + Array(5).fill('<td>&nbsp;</td>').join('') + '</tr>').join('\n')}
    </table>

    <h2>3. Backup Status</h2>
    <table>
      <tr>
        <th>System / Data</th>
        <th>Backup Method</th>
        <th>Frequency</th>
        <th>Last Tested</th>
        <th>Recovery Time</th>
      </tr>
      ${Array(8).fill('').map(() => '<tr>' + Array(5).fill('<td>&nbsp;</td>').join('') + '</tr>').join('\n')}
    </table>

    <div class="section">
      <h3>Emergency Contact Plan</h3>
      <p>If the main IT person is unavailable, contact:</p>
      <p>Name: <span class="input-field">________________</span> Phone: <span class="input-field">________________</span></p>
      <p>Name: <span class="input-field">________________</span> Phone: <span class="input-field">________________</span></p>
    </div>

    <p class="note">Created using the Kamunity Digital Sovereignty Toolkit (kamunity-audit.netlify.app).</p>
  `;
  downloadHtmlAsDoc('Data-Location-Map-Template.doc', html);
}

export function downloadCostAuditTemplate() {
  const html = `
    <h1>Digital Cost Audit Worksheet</h1>
    <p class="note">Generated by the Kamunity Cost Transparency Toolkit. Track what you're spending on digital tools.</p>

    <h2>1. Current Subscriptions</h2>
    <table>
      <tr>
        <th>Tool / Service</th>
        <th>Monthly Cost</th>
        <th>Annual Cost</th>
        <th>Billing Cycle</th>
        <th>NFP Discount Available?</th>
        <th>Renewal Date</th>
      </tr>
      ${Array(15).fill('').map(() => '<tr>' + Array(6).fill('<td>&nbsp;</td>').join('') + '</tr>').join('\n')}
    </table>

    <p><strong>Total Monthly:</strong> $<span class="input-field">____</span> &nbsp;&nbsp; <strong>Total Annual:</strong> $<span class="input-field">____</span></p>

    <h2>2. Hidden Costs</h2>
    <table>
      <tr>
        <th>Cost Type</th>
        <th>Estimated Hours/Month</th>
        <th>Estimated $ Value</th>
        <th>Notes</th>
      </tr>
      <tr><td>IT administration time</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Training new staff on tools</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Manual workarounds</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Integration / connector tools</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Data cleanup / migration</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    </table>

    <h2>3. Savings Opportunities</h2>
    <table>
      <tr>
        <th>Action</th>
        <th>Current Cost</th>
        <th>After Change</th>
        <th>Annual Saving</th>
        <th>Effort Required</th>
      </tr>
      <tr><td>Apply for NFP discounts</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Consolidate duplicate tools</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Cancel unused subscriptions</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>Switch to free alternatives</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
      <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    </table>

    <div class="section">
      <h3>Grant Reporting Note</h3>
      <p>Total digital infrastructure cost for grant budgets: $<span class="input-field">____</span>/year</p>
      <p>Staff time on IT administration: <span class="input-field">____</span> hours/month = $<span class="input-field">____</span>/year</p>
    </div>

    <p class="note">Created using the Kamunity Digital Sovereignty Toolkit (kamunity-audit.netlify.app).</p>
  `;
  downloadHtmlAsDoc('Cost-Audit-Worksheet-Template.doc', html);
}
